Homework3_zc2823
================
2025-10-07

# Problem 1

Loading data and read ‘instacart’

``` r
data("instacart")
```

### Size and Structure of the data

``` r
n_obs <- nrow(instacart)
n_vars <- ncol(instacart)

glimpse(instacart)
```

    ## Rows: 1,384,617
    ## Columns: 15
    ## $ order_id               <int> 1, 1, 1, 1, 1, 1, 1, 1, 36, 36, 36, 36, 36, 36,…
    ## $ product_id             <int> 49302, 11109, 10246, 49683, 43633, 13176, 47209…
    ## $ add_to_cart_order      <int> 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,…
    ## $ reordered              <int> 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,…
    ## $ user_id                <int> 112108, 112108, 112108, 112108, 112108, 112108,…
    ## $ eval_set               <chr> "train", "train", "train", "train", "train", "t…
    ## $ order_number           <int> 4, 4, 4, 4, 4, 4, 4, 4, 23, 23, 23, 23, 23, 23,…
    ## $ order_dow              <int> 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6,…
    ## $ order_hour_of_day      <int> 10, 10, 10, 10, 10, 10, 10, 10, 18, 18, 18, 18,…
    ## $ days_since_prior_order <int> 9, 9, 9, 9, 9, 9, 9, 9, 30, 30, 30, 30, 30, 30,…
    ## $ product_name           <chr> "Bulgarian Yogurt", "Organic 4% Milk Fat Whole …
    ## $ aisle_id               <int> 120, 108, 83, 83, 95, 24, 24, 21, 2, 115, 53, 1…
    ## $ department_id          <int> 16, 16, 4, 4, 15, 4, 4, 16, 16, 7, 16, 4, 16, 2…
    ## $ aisle                  <chr> "yogurt", "other creams cheeses", "fresh vegeta…
    ## $ department             <chr> "dairy eggs", "dairy eggs", "produce", "produce…

### Examples of observations

``` r
example_rows <- instacart |> 
  slice_sample(n = 5)

example_rows
```

    ## # A tibble: 5 × 15
    ##   order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##      <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ## 1  1107870      33731                 6         0  197159 train               5
    ## 2   304371      28199                 2         1   46980 train              10
    ## 3  2113105      44669                13         1   51853 train              60
    ## 4    60897      36011                 7         1  141234 train              16
    ## 5  3319391       6873                 7         1  171343 train              11
    ## # ℹ 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

#### Short Description of the data

The Instacart dataset contains information on 1,384,617 observations and
15 variables, each corresponding to a single product added to a
customer’s online grocery order. Each row represents one product within
an order, while columns describe identifiers, product details, and
timing information for that purchase, and multiple rows can belong to
the same order or user.

Key variables include `order_id` and `user_id` for identifying orders
and customers, `product_name` describing the purchased items, `aisle`
and `department` indicating the product’s physical or categorical
location within the store (for example, yogurt in the dairy eggs
department), and `order_dow` and `order_hour_of_day` capturing when the
purchases occurred. Also, the variable `reordered` flags whether the
product had been previously purchased by the same user.

For example, a sample of five observations shows that user 197159 placed
an order (`order_id` 1107870) where `product_id` 33731 was added as the
6th item in the cart and was not ordered by this user in the past.
